apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-job0
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: post-install
          image: alpine:latest
          command: ["sleep", "20"]
      restartPolicy: OnFailure
  backoffLimit: 0
